[tool.poetry]
name = "gordo-core"
version = "0.1.0"
description = "Gordo core library"
authors = ["Equinor ASA <fg_gpl@equinor.com>"]
license = "AGPLv3"
readme = "README.md"
homepage = "https://github.com/equinor/gordo-core"
repository = "https://github.com/equinor/gordo-core"
keywords = ["gordo-core"]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
include = [
    "LICENSE",
]
packages = [
    { include = "gordo_core" }
]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "~1.4.0"
influxdb = ">=5.3.0,<6.0.0"
cachetools = ">=4.1.0,<5.0.0"
pyarrow = ">=3.0.0,<7.0.0"
PyYAML = "^5.3.1"
scikit-learn = ">=0.24.2,<1.0.0"
numexpr = "^2.8.1"
xarray = "^2022.3.0"
pydantic = "^1.8.2"
numpy = "^1.22.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
